mindmap
  root((Login Functionality))
    Analysis and Planning
      Objective
        Requirement
        Risk based
        Hybrid
      In Scope
        Customer journeys
        Testing layers
      Out of Scope
        Social media login
        Multi-factor authentication
      Risks and dependencies
        People
        Process
        Product
      Timescales
        Internal
        UAT
        External
    Execution and Test Summary
      Testing types
        Automation
        Exploratory
        Other
      Tools
        Testing
        Defect
      Environment Setup