graph TD
    Sandwiches --> Fillings
    Sandwiches --> Bread
    Sandwiches --> Cost
    Fillings --> Egg_Mayo
    Fillings --> Bacon
    Fillings --> Cheese_and_Pickle

    Egg_Mayo[Egg Mayo]
    Cheese_and_Pickle[Cheese and Pickle]